### ISSUE TITLE
cl-css enters infinite recursion on a rule without body

### ISSUE THREAD

**Issue by orivej** [inaimathi/cl-css#4]
This enters infinite recursion: `(cl-css:css '((body)))`
Noticed it on `("#table-players li .hand-size")` in `deal-ui/css.lisp`.
Fix the loop in `format-declarations-list` in `cl-css.lisp`like this:

``` lisp
        if (consp head) collect (format-rule (car head) (cdr head))
        else if head collect (format-declaration head (pop remaining))
```

**Comment by inaimathi** [comment]
Pardon the delay.

I can't repro this with the latest version of `cl-css`. On my local, `(cl-css:css '((body)))` evaluates to 

```
"body { }
"
```

Any ideas?

**Comment by orivej** [comment]
I might guess that your local copy is different from the latest commited version.
Here is a beginning of the traceback:

```
cl-css> (trace format-declarations-list format-rule format-declaration)
(format-declarations-list format-rule format-declaration)
cl-css> (css '((body)))
  0: (format-rule body nil)
    1: (format-declarations-list nil)
      2: (format-rule nil nil)
        3: (format-declarations-list nil)
          4: (format-rule nil nil)
```

**Comment by inaimathi** [comment]
You are correct; I had a stale install of an older version of `cl-css`.

Confirmed that this caused an infinite recursion, and that your suggestion fixes it.

The patch has been committed, and the ASDF package has been updated.
